### PR TITLE
docs: specify only gensets for boiler/heater

### PR DESCRIPTION
**Pull request by frodehk**
## Why is this pull request needed?

Clarify that boilers and heaters should be modeled as generator sets only.

## What does this pull request change?

Remove description of heater/boiler modeled as fuelconsumers.

## Issues related to this change:
https://github.com/equinor/ecalc-engine/issues/4384

### CODE REVIEW

**Review by TeeeJay — APPROVED** [review]
@halsyl  has permission to approve this one if she is happy with current description :)

**Comment by halsyl** [comment]
The Installations section looks good, @frodehk :)

For the CATEGORY section, it may be better to stick to the phrase already used for similar cases (i.e. change from "Model as GENERATORSETS" to "Genset only"). I also think this is better because the section is not supposed to inform on _how_ we're modelling heaters/boilers, rather where to apply the CATEGORY keywords.

Not sure if I'm able to edit the text myself, and if you'd like me to do that...?

**Comment by frodehk** [comment]
@halsyl: I have just updated it now:-)

**Comment by halsyl** [comment]
No clue how to approve this one, but the green button seemed alluring :) Hope it is OK. Thanks for fixing, @frodehk!

**Pull request merged**
